
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal"
		title="close window">
		<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
	</button>
	<h2 id="myModalLabel" class="modal-title">Add Service Record</h2>

	<div class="modal-body">

		<?php $form = $this->form;?>
		<?php $form->prepare();?>
		<?php echo $this->form()->openTag($form);?>
		
		<div class="form-group">
			<div class="col-md-3 control-label"><?php echo $this->formlabel($form->get('date'))?></div>
			<div class="col-md-9 editor-field"><?php echo $this->formelement($form->get('date'))?></div>
		</div>

		<div class="form-group">
			<div class="col-md-3 control-label"><?php echo $this->formlabel($form->get('supplierid'))?></div>
			<div class="col-md-9 editor-field"><?php echo $this->formelement($form->get('supplierid'))?></div>
		</div>

		<div class="form-group">
			<div class="col-md-3 control-label"><?php echo $this->formlabel($form->get('comments'))?></div>
			<div class="col-md-9 editor-field"><?php echo $this->formelement($form->get('comments'))?></div>
		</div>

		<div class="form-group">
			<div class="col-md-3 control-label"><?php echo $this->formlabel($form->get('cost'))?></div>
			<div class="col-md-9 editor-field"><?php echo $this->formelement($form->get('cost'))?></div>
		</div>

		<div class="form-group">
			<div class="col-md-3 control-label"><?php echo $this->formlabel($form->get('invoicenumber'))?></div>
			<div class="col-md-9 editor-field"><?php echo $this->formelement($form->get('invoicenumber'))?></div>
		</div>

		<div class="form-group">
			<div class="col-md-3 control-label"><?php echo $this->formlabel($form->get('odometer'))?></div>
			<div class="col-md-9 editor-field"><?php echo $this->formelement($form->get('odometer'))?></div>
		</div>

		<div class="modal-footer">
			<button type="button" class="btn btn-primary" data-dismiss="modal"
				title="Close this window">
				<span class="glyphicon glyphicon-remove"></span>&nbsp;Close
			</button>
			<button type="submit" class="btn btn-primary" title="Save changes">
				<span class="glyphicon glyphicon-save"></span>&nbsp;Save
			</button>
			<input type="hidden" name="car" value="<?php echo $this->car;?>" />
		</div>
		
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$('#servicedate').datepicker({
		dateFormat:'dd/mm/yy'
	});
});
				</script>