<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 ' . $this->translate('My Cars application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->appendStylesheet($this->basepath() . '/css/bootstrap-datepicker.min.css')
        ->appendStylesheet($this->basePath() . '/css/style.css') ?>

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" type="text/javascript"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"
            type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.js"></script>
    <script type="text/javascript">
        $.ajaxSetup({cache: false});
    </script>

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img
                        src="<?php echo $this->basePath('img/zf2-logo.png') ?>"
                        alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('My Cars Application') ?></a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a>
                </li>
                <li><a href="<?php echo $this->url('cars') ?>"><?php echo $this->translate('Cars') ?></a></li>
                <li><a href="<?php echo $this->url('service') ?>"><?php echo $this->translate('Service') ?></a></li>
                <li><a href="<?php echo $this->url('album') ?>"><?php echo $this->translate('Album') ?></a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="container">
    <?php echo $this->content; ?>
    <hr>
    <footer>
        <p>&copy; 2014 - <?php echo date('Y') ?> by Jon. <?php echo $this->translate('All rights reserved.') ?></p>
    </footer>
</div> <!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
