<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Cars\Module'                        => __DIR__ . '/Module.php',
    'Cars\Controller\IndexController' => __DIR__ . '/src/Cars/Controller/IndexController.php',
    'CarsTest\Framework\TestCase'        => __DIR__ . '/tests/Cars/Framework/TestCase.php',
    'CarsTest\SampleTest'                => __DIR__ . '/tests/Cars/SampleTest.php',
);
