<section>
	<div class="panel panel-primary panel-secondary">
		<div class="panel-heading">Enter Details of a New Car</div>
		<div class="panel-body">
<?php
$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
				<div class="col-md-3 control-label"><?php echo $this->formlabel($form->get('make'))?></div>
				<div class="col-md-9"><?php echo $this->formelement($form->get('make'))?></div>
			</div>

			<div class="form-group">
				<div class="col-md-3 control-label"><?php echo $this->formlabel($form->get('model'))?></div>
				<div class="col-md-9"><?php echo $this->formelement($form->get('model'))?></div>
			</div>

			<div class="form-group">
				<div class="col-md-3 control-label"><?php echo $this->formlabel($form->get('transmission'))?></div>
				<div class="col-md-9"><?php echo $this->formelement($form->get('transmission'))?></div>
			</div>

			<div class="form-group">
				<div class="col-md-3 control-label"><?php echo $this->formlabel($form->get('cylinders'))?></div>
				<div class="col-md-9"><?php echo $this->formelement($form->get('cylinders'))?></div>
			</div>

			<div class="form-group">
				<div class="col-md-3 control-label"><?php echo $this->formlabel($form->get('enginesize'))?></div>
				<div class="col-md-9"><?php echo $this->formelement($form->get('enginesize'))?></div>
			</div>

			<div class="form-group">
				<div class="col-md-3 control-label"><?php echo $this->formlabel($form->get('bodytype'))?></div>
				<div class="col-md-9"><?php echo $this->formelement($form->get('bodytype'))?></div>
			</div>

			<div class="form-group">
				<div class="col-md-3 control-label"><?php echo $this->formlabel($form->get('image'))?></div>
				<div class="col-md-9"><?php echo $this->formelement($form->get('image'))?></div>
			</div>

			<div class="form-group">
				<div class="col-md-3 control-label"><?php echo $this->formlabel($form->get('license'));?></div>
				<div class="col-md-9"><?php
    
    echo $this->formelement($form->get('license'));
    echo $this->formelementerrors($form->get('license'));
    ?>
				</div>
			</div>

			<div class="form-group">
				<div class="col-md-3 control-label"><?php echo $this->formlabel($form->get('purchased'));?></div>
				<div class="col-md-9"><?php
    
    echo $this->formelement($form->get('purchased'));
    echo $this->formelementerrors($form->get('purchased'));
    ?>
				</div>
			</div>

			<div class="form-group">
				<div class="col-md-3 control-label"><?php echo $this->formlabel($form->get('modelyear'));?></div>
				<div class="col-md-9"><?php
    
    echo $this->formelement($form->get('modelyear'));
    echo $this->formelementerrors($form->get('modelyear'));
    ?>
				</div>
			</div>

			<div class="form-group">
				<div class="col-md-3 control-label"><?php echo $this->formlabel($form->get('cost'));?></div>
				<div class="col-md-9"><?php
    
    echo $this->formelement($form->get('cost'));
    echo $this->formelementerrors($form->get('cost'));
    ?>
				</div>
			</div>

			<div class="form-group">
				<div class="col-md-offset-3 col-md-9">
					<button type="submit" class="btn default" title="Save changes">
						<span class="glyphicon glyphicon-save"></span>&nbsp;Save
					</button>
				</div>
			</div>
	
<?php echo $this->form()->closeTag(); ?>
</div>
	</div>
</section>
<script type="text/javascript">
$(document).ready(function(){
	$('#purchased').datepicker({
		dateFormat:'dd/mm/yy'
	});
});
				</script>