<h1><?php echo $this->car->getMake(). ' '.$this->car->getModel()?></h1>
<div>
	<img
		src="<?php echo $this->basePath() . '/img/'.$car->getImage().'.jpg';?>"
		alt="<?php echo $car->getMake() . ' '.$car->getModel()?>"
		title="<?php echo $car->getModelYear().' '. $car->getMake() . ' '.$car->getModel()?>" />
</div>
<?php
echo $this->car->getLicense();
echo $this->car->getMake();
echo $this->car->getModel();
echo $this->car->getCost();
echo $this->car->getEngineSize();
echo $this->car->getModelYear();
echo $this->car->getTransmission();
echo $this->car->getId();
echo $this->car->getImage();

